apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-default-backend
spec:
  replicas: 1
  template: 
    metadata:
      labels:
        app: nginx
        role: nginx-default-backend
    spec:
      containers:
      - name: ingress-default-backend
        image: nginx
        ports:
        - containerPort: 80
